/**
 * Created by st0001 on 2016/10/25.
 */
public enum TokenType {
    PLUS, MINUS, TIMES, DIVIDE,
    GT, LT, ASSIGN, LBRACKET, RBRACKET,
    LBRACE, RBRACE, LSBRACKET, RSBRACKET,
    COMMA, SEMICOLON, NOTE, RESERVED,
    NUM,ID
}
